import math
import sys

import numpy as np
import torch
import torch.nn.functional as F
from scipy import interpolate


def geometric_progression(a, r, n):
    return a * (1.0 - r**n) / (1.0 - r)


def geometric_sequence_interpolation(src_size, dst_size, sequence, num):
    left, right = 1.01, 1.5
    while right - left > 1e-6:
        q = (left + right) / 2.0
        gp = geometric_progression(1, q, src_size // 2)
        if gp > dst_size // 2:
            right = q
        else:
            left = q
    dis = []
    cur = 1
    for i in range(src_size // 2):
        dis.append(cur)
        cur += q**(i + 1)
    r_ids = [-_ for _ in reversed(dis)]
    x = np.array(r_ids + [0] + dis, dtype=np.float64)
    y = np.array(r_ids + [0] + dis, dtype=np.float64)
    t = dst_size // 2.0
    dx = np.arange(-t, t + 0.1, 1.0)
    dy = np.arange(-t, t + 0.1, 1.0)
    new_sequence = []
    for i in range(num):
        z = sequence[:, i].view(src_size, src_size).float().numpy()
        f = interpolate.RectBivariateSpline(x, y, z, kx=3, ky=3)
        new_sequence.append(
            torch.Tensor(f(dx, dy)).contiguous().view(-1, 1).to(sequence))
    new_sequence = torch.cat(new_sequence, dim=-1)
    return new_sequence


def resize_abs_pos_embed(state_dict, dst_patch_size):
    if 'backbone.pos_embed' in state_dict:
        key = 'backbone.pos_embed'
    elif 'pos_embed' in state_dict:
        key = 'pos_embed'
    else:
        print('No pos_embed found in checkpoint, skipping abs pos embed resize')
        return state_dict

    pos_embed_checkpoint = state_dict[key]
    embedding_size = pos_embed_checkpoint.shape[-1]
    num_extra_tokens = 1  # cls_token
    orig_size = int((pos_embed_checkpoint.shape[-2] - num_extra_tokens)**0.5)
    new_size = dst_patch_size

    if orig_size == new_size:
        print(f'pos_embed size matches ({orig_size}x{orig_size}), no resize needed')
        return state_dict

    print(f'Resizing abs pos_embed: {orig_size}x{orig_size} -> {new_size}x{new_size}')
    extra_tokens = pos_embed_checkpoint[:, :num_extra_tokens]
    pos_tokens = pos_embed_checkpoint[:, num_extra_tokens:]
    pos_tokens = pos_tokens.reshape(-1, orig_size, orig_size,
                                    embedding_size).permute(0, 3, 1, 2)
    pos_tokens = F.interpolate(
        pos_tokens, size=(new_size, new_size), mode='bicubic', align_corners=False)
    pos_tokens = pos_tokens.permute(0, 2, 3, 1).flatten(1, 2)
    new_pos_embed = torch.cat((extra_tokens, pos_tokens), dim=1)
    state_dict[key] = new_pos_embed
    print(f'  pos_embed shape: {pos_embed_checkpoint.shape} -> {new_pos_embed.shape}')
    return state_dict


def resize_rel_pos_embed(state_dict, dst_patch_size):
    all_keys = list(state_dict.keys())
    for key in all_keys:
        if 'relative_position_index' in key:
            print(f'Removing: {key} (will be regenerated by model)')
            state_dict.pop(key)

        if 'relative_position_bias_table' in key:
            rel_pos_bias = state_dict[key]
            src_num_pos, num_attn_heads = rel_pos_bias.size()

            num_extra_tokens = 3
            dst_num_pos = (2 * dst_patch_size - 1) * (2 * dst_patch_size - 1) + num_extra_tokens

            src_size = int((src_num_pos - num_extra_tokens)**0.5)
            dst_size = int((dst_num_pos - num_extra_tokens)**0.5)

            if src_size == dst_size:
                print(f'{key}: size matches ({src_size}x{src_size}), no resize needed')
                continue

            print(f'Resizing rel pos bias: {key} {src_size}x{src_size} -> {dst_size}x{dst_size}')
            extra_tokens = rel_pos_bias[-num_extra_tokens:, :]
            rel_pos_bias = rel_pos_bias[:-num_extra_tokens, :]
            new_rel_pos_bias = geometric_sequence_interpolation(
                src_size, dst_size, rel_pos_bias, num_attn_heads)
            new_rel_pos_bias = torch.cat((new_rel_pos_bias, extra_tokens), dim=0)
            state_dict[key] = new_rel_pos_bias
            print(f'  shape: {rel_pos_bias.shape} -> {new_rel_pos_bias.shape}')

    return state_dict


def convert_checkpoint(src_path, dst_path, dst_img_size=480, patch_size=16):
    dst_patch_size = dst_img_size // patch_size
    print(f'Converting checkpoint: {src_path}')
    print(f'Target: {dst_img_size}x{dst_img_size} (patch: {dst_patch_size}x{dst_patch_size})')
    print()

    ckpt = torch.load(src_path, map_location='cpu')
    if 'state_dict' in ckpt:
        state_dict = ckpt['state_dict']
    elif 'model' in ckpt:
        state_dict = ckpt['model']
    else:
        state_dict = ckpt

    state_dict = resize_abs_pos_embed(state_dict, dst_patch_size)
    state_dict = resize_rel_pos_embed(state_dict, dst_patch_size)

    if 'state_dict' in ckpt:
        ckpt['state_dict'] = state_dict
    elif 'model' in ckpt:
        ckpt['model'] = state_dict
    else:
        ckpt = state_dict

    torch.save(ckpt, dst_path)
    print(f'\nConverted checkpoint saved to: {dst_path}')


if __name__ == '__main__':
    src_path = '/home/lh/code/QWSEG/seg/mmsegmentation-main-rgbt/pretrain/FMB_save_iter_224000.pth'
    dst_path = '/home/lh/code/QWSEG/seg/mmsegmentation-main-rgbt/pretrain/FMB_save_iter_224000_480x480.pth'

    convert_checkpoint(src_path, dst_path, dst_img_size=480, patch_size=16)
